/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ArtEmptyState: typeof import('./components/business/ArtEmptyState.vue')['default']
    DataTable: typeof import('./components/business/DataTable.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FilterPanel: typeof import('./components/business/FilterPanel.vue')['default']
    KpiCard: typeof import('./components/business/KpiCard.vue')['default']
    MonthRangePicker: typeof import('./components/MonthRangePicker/index.vue')['default']
    PageContainer: typeof import('./components/layout/PageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleBarChart: typeof import('./components/charts/SimpleBarChart.vue')['default']
    SimpleLineChart: typeof import('./components/charts/SimpleLineChart.vue')['default']
    SimplePieChart: typeof import('./components/charts/SimplePieChart.vue')['default']
    StatusTag: typeof import('./components/business/StatusTag.vue')['default']
  }
}
